### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by OxDuke** [lmontaut/collision-detection-benchmark#1]
I come from the RSS 2022 paper, and I have been trying to run the benchmark on a freshly installed Ubuntu20.04. I am strictly following the installation guidelines. However, during the cmake stage, the following dependencies are missing:

- CMake can't find eigenpy, which I fixed by running `conda install eigenpy -c conda-forge`.
- CMake can't find qhull, which I fixed by installing qhull from source using CMake (see https://github.com/qhull/qhull). Note that `sudo apt install libqhull-dev` won't work, because the package does not contain CMakeConfig files (See https://packages.ubuntu.com/focal/amd64/libqhull-dev/filelist). We might be able to fix the apt installed problem by providing a FindQhull.cmake, but that's another story.

I hope the missing dependencies mentioned above could be added readme.

**Comment by lmontaut** [comment]
Hi @OxDuke, thanks for your interest in the paper & in this repo.
I remade a conda env from scratch and when doing `conda install cmake pinocchio ...` the dependency `eigenpy` is found and installed by conda. If I reload the conda env `conda activate ...`, CMake finds `eigenpy` flawlessly on my side. 
In fact `eigenpy` is a required dependency of Pinocchio so it's weird that you had to (re)-install it yourself.
Regarding qhull, you can `conda install qhull`. I will add that to the readme, thanks.
